### ISSUE TITLE
Does this implement imitation learning?

### ISSUE THREAD

**Issue by jlabhishek** [sjtuytc/AAAI21-RoutineAugmentedPolicyLearning#1]
I was looking at the code, but I could not understand - is the code doing imitation learning or just training vanilla rl with routines?
Can you kindly throw some light on this , and maybe on relevant sections if it does do imitation learning

**Comment by sjtuytc** [comment]
It's RAPL-A2C (Page 4 in our paper). We do not plan to release RAPL-SQIL as the SQIL is not a public code. We get the SQIL code from the authors of SQIL, which cannot be released by us.
